FROM nginx
COPY html /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
COPY backend-not-found.html /usr/share/nginx/html/backend-not-found.html
COPY includes /etc/nginx/includes/
